import os
import json
import logging
from datetime import datetime
from typing import Dict, Any

logger = logging.getLogger(__name__)

WORKSPACE_DIR = os.path.abspath(os.path.join(os.path.dirname(__file__), "..", "..", "data", "workspace"))
TASKS_DIR = os.path.join(WORKSPACE_DIR, "tasks")
BRIEFS_DIR = os.path.join(WORKSPACE_DIR, "briefs")

class LocalToolService:
    @staticmethod
    def ensure_directories():
        os.makedirs(TASKS_DIR, exist_ok=True)
        os.makedirs(BRIEFS_DIR, exist_ok=True)

    @staticmethod
    def execute_create_task(action_id: str, payload: Dict[str, Any]) -> Dict[str, Any]:
        """
        Creates a structured local task record.
        """
        LocalToolService.ensure_directories()
        
        file_path = os.path.join(TASKS_DIR, f"{action_id}.json")
        
        if os.path.exists(file_path):
            raise FileExistsError("Task already exists (duplicate execution attempt).")
            
        task_data = {
            "action_id": action_id,
            "task_title": payload.get("task_title"),
            "notes": payload.get("notes"),
            "due_date": payload.get("due_date"),
            "created_at": datetime.utcnow().isoformat()
        }
        
        with open(file_path, "w") as f:
            json.dump(task_data, f, indent=4)
            
        logger.info(f"Created task file at {file_path}")
        return {
            "task_id": action_id,
            "message": "Task created locally.",
            "file_path": file_path
        }

    @staticmethod
    def execute_save_brief(action_id: str, payload: Dict[str, Any]) -> Dict[str, Any]:
        """
        Saves a local brief text document.
        """
        LocalToolService.ensure_directories()
        
        # Use safe filename generated by backend (action_id is a UUID usually)
        file_path = os.path.join(BRIEFS_DIR, f"brief_{action_id}.txt")
        
        if os.path.exists(file_path):
            raise FileExistsError("Brief already exists (duplicate execution attempt).")
            
        content = payload.get("content", "")
        title = payload.get("title", "Untitled Brief")
        
        full_content = f"TITLE: {title}\n\n{content}\n"
        
        with open(file_path, "w") as f:
            f.write(full_content)
            
        logger.info(f"Created brief file at {file_path}")
        return {
            "brief_id": action_id,
            "message": "Brief saved locally.",
            "file_path": file_path
        }
